util.h: fix MAX_URI_SIZE sizeof usage
Fix for :

inc/request.h:131:14: error: sizeof on pointer operation will return
 size of 'char *' instead of 'char [9]' [-Werror,-Wsizeof-array-decay]

Signed-off-by: Danny Al-Gaaf <danny.al-gaaf@bisect.de>